
name: AWS Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Name of the branch to deploy"
        type: string
        default: main

permissions:
  id-token: write
  contents: read
  deployments: write
  
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"

  deploy:
    runs-on: 
      labels: [ubuntu-latest]
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.REGION }}
          role-session-name: github-actions-${{ github.run_id }}

      - name: List S3 Buckets
        run: |
          echo "Listing s3 buckets"
          aws s3 ls